//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyTutor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MyTutor_Profile
    {
        public int Id { get; set; }
        public int TutorId { get; set; }
        public string HighestEducation { get; set; }
        public string Medium { get; set; }
        public string ClassFrom { get; set; }
        public string ClassTo { get; set; }
        public string Subjects { get; set; }
        public string Experience { get; set; }
        public string ResumePath { get; set; }
        public string Description { get; set; }
    }
}
