//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyTutor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MyTutor_ContactUs
    {
        public int Id { get; set; }
        public string EmailId { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<bool> IsAnswered { get; set; }
    }
}
