//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyTutor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MyTutor_Registration
    {
        public int Id { get; set; }
        public string FullName { get; set; }
        public string MobileNumber { get; set; }
        public string Address { get; set; }
        public string Area { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public string ProfilePicPath { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public Nullable<int> StateId { get; set; }
        public Nullable<int> CityId { get; set; }
        public Nullable<int> AreaId { get; set; }
        public string VerificationCode { get; set; }
        public Nullable<bool> IsValidated { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsAccountSuspended { get; set; }
    }
}
