//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyTutor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MyTutor_GetContactInformation
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string MobileNo { get; set; }
        public string Descriptions { get; set; }
        public int TutorId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<bool> IsEmailSend { get; set; }
    }
}
