//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyTutor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MyTutor_CityList
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MyTutor_CityList()
        {
            this.MyTutor_AreaList = new HashSet<MyTutor_AreaList>();
        }
    
        public int CityId { get; set; }
        public string CityName { get; set; }
        public int StateId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MyTutor_AreaList> MyTutor_AreaList { get; set; }
        public virtual MyTutor_StateList MyTutor_StateList { get; set; }
    }
}
