//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyTutor.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MyTutorDBEntities : DbContext
    {
        public MyTutorDBEntities()
            : base("name=MyTutorDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MyTutor_AreaList> MyTutor_AreaList { get; set; }
        public virtual DbSet<MyTutor_CityList> MyTutor_CityList { get; set; }
        public virtual DbSet<MyTutor_ContactUs> MyTutor_ContactUs { get; set; }
        public virtual DbSet<MyTutor_Profile> MyTutor_Profile { get; set; }
        public virtual DbSet<MyTutor_Registration> MyTutor_Registration { get; set; }
        public virtual DbSet<MyTutor_StateList> MyTutor_StateList { get; set; }
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<MyTutor_GetContactInformation> MyTutor_GetContactInformation { get; set; }
    }
}
