//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyTutor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MyTutor_AreaList
    {
        public int AreaId { get; set; }
        public string AreaName { get; set; }
        public Nullable<int> CityId { get; set; }
    
        public virtual MyTutor_CityList MyTutor_CityList { get; set; }
    }
}
